authapp/urls.py
from django.urls import path  # importing the path funtion from Django's urls module.
from django.urls import reverse_lazy
from . import views
#from . import views

# Importing various views for handling authentication related funtionality from Django's auth.view module
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
    PasswordResetCompleteView, PasswordResetConfirmView,
    PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView
)

# Importing the views funtion for edit, dashboard, register.  
from .views import edit, dashboard, register                                     

# Defining the 'authapp' namespace for the urlpatterns in this module.
app_name = 'authapp'

# Defining the urlpatterns for this module.
urlpatterns = [

    # Mapping the URL path 'register/' to the register view function.
    path('register/', register, name='register'), 
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),

    # Mapping the root URL path to the LoginView to provide Django's authentication framework
    # Using a custom login tempalte and the 'login' URL name.
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'), 
    path('logout/', LogoutView.as_view(template_name='authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),

    # Mapping the URL path 'passowrd_reset/' to the PasswordResetView to provide Django's authentication framework.
    # Using a custom password_reset_form template, a custom password_reset_email template, and the 'password_reset' URL name,
    # and specifying the success URL using the reverse_lazy function and the 'password_reset_done' URL name.     
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),  

          
     path('item/', views.item, name="item"),
]

src/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
#from django.conf.global_settings import LANGUAGE
 
urlpatterns = [
   # path('', include('authapp.urls', namespace='authapp')),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
  
]

urlpatterns += i18n_patterns (
    path('', include('authapp.urls', namespace='authapp'))
)

authapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField

# Create your models here.

class UserType(models.Model):
    Clients = 1
    Artists = 2
    TvChannel = 3
    RadioChannel = 4
    TYPE_CHOICES = (
        (Artists, 'Artists'),
        (Clients, 'Clients'),
        (TvChannel, 'TVChannel'),
        (RadioChannel, 'RadioChannel')
    )
    id = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, primary_key=True)
    
    def __str__(self):
        return self.get_id_display()

    
    

class UserRegistrationModel(models.Model):
    # Creating a one-to-one relationship with the User model in the database
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    # Defining the view_artist permission
    class Meta:
         permissions=[("view_artist","View the artists")] 

    # Defining the create_project permission         
    class Meta:
        permissions=[("create_project","Create new project")]  

# Creating the Artist model
class Artist(models.Model):

    # Defining the name field
    name=models.CharField(max_length=120)

    # Defining the type field
    type=models.CharField(max_length=120)

    # Defining the active field with a default value of True
    active=models.BooleanField(default=True)
    
    # Defining the string representation of the model
    def __str__(self):
        return self.name

usertype = models.ManyToManyField(UserType)    

# Creating the Client model
class Client(models.Model):

    # Defining the name field
    name=models.CharField(max_length=120)

    # Defining the description field with blank and null values allowed
    description=models.TextField(blank=True,null=True)

    # Defining the active field with a default value of True
    active=models.BooleanField(default=True)
    
    # Defining the string representation of the model
    def __str__(self):
        return self.name        

# Creating the TvChannel model
class TvChannel(models.Model):

    # Defining the name field
    name=models.CharField(max_length=120)

    #Defining the description field with blank and null values allowed
    description=models.TextField(blank=True,null=True)

    #Defining the active field with a default value of true
    active=models.BooleanField(default=True)
    
    # Defining the string representation of the model
    def __str__(self):
        return self.name                

# Creating the RadioChannel model
class RadioChannel(models.Model):

    # Defining the name field
    name=models.CharField(max_length=120)

    #Defining the description field with blank and null values allowed
    description=models.TextField(blank=True,null=True)

    #Defining the active field with a default value of true
    active=models.BooleanField(default=True)
    
    # Defining the string representation of the model
    def __str__(self):
        return self.name  

              

authapp/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm


class UserRegistration(forms.ModelForm):
    # This form field is for the password
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    # This form field is for confirming the password
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    # This is the Meta class for the form, it defines the model and the fields that should be displayed in the form
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        # This method is used for password confirmation validation
        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']

# This is a form for editing the user's information
class UserEditForm(forms.ModelForm):

    # This is the Meta class for the form, it defines the model and the fields that should be displayed in the form
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


        



 


      

authapp/views.py
# Import necessary module
from django.http import request 
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm
from django.conf import settings
from django.core.mail import send_mail


# Create your views here

@login_required
def dashboard(request):

    # Create context dictionary to pass variables to the template
    context = {
        "welcome": "Welcome to your dashboard"
    }

    # Render the dashboard.html template with context
    return render(request, 'authapp/dashboard.html', context=context)

# Function to handle registration 
def register(request):

    # Check if the request is a POST request
    if request.method == 'POST':

        # Create UserRegistration form object with post data.
        form = UserRegistration(request.POST or None)

        # Check if form is valid.
        if form.is_valid():

            # Create a new_user object without committing to database. 
            new_user = form.save(commit=False)

            # Set the user password using the cleaned_data from the form. 
            new_user.set_password(
                form.cleaned_data.get('password')
            )

            # save the user to the database.
            new_user.save()

            # Render the register_done.html template.
            return render(request, 'authapp/register_done.html')
    else:

        # If the request is not a POST request, create a new UserRegistration form object
        form = UserRegistration()
    
    # Create a context dictionary to pass variables to the template.
    context = {
        "form": form
    }
     
    # Render the register.html template with context. 
    return render(request, 'authapp/register.html', context=context)


@login_required
# Function to handle edit.
def edit(request):

    # Check if the request is a POST request.
    if request.method == 'POST':

        # Create UserRegistration form object with post data and current user instance
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        # Check if the form is valid.                         
        if user_form.is_valid():
            user_form.save()
    else:

        # if request is not POST , Create a new UserEditForm without current user instance
        user_form = UserEditForm(instance=request.user)

    # Create a context dictionary to pass variables to the template.    
    context = {
        'form': user_form,
    }

    # Render the edit.html template with context. 
    return render(request, 'authapp/edit.html', context=context)

from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext
from django.utils import translation

def item(request):
    trans = translate(language='fr')
    return render(request, 'item.html', {'trans':trans})


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
        text = gettext('hello')
    finally:
        activate(cur_language)
    return text        

authapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">

    
    
        <!-- CSS -->
    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}">
    -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>App {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    
</body>

</html>

authapp/templates/home.html
{% load static %}
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

{% endblock content %}

authapp/templates/item.html
{% load i18n %} <!-- Add this line to load the i18n template library -->
{% load static %} 
<!doctype html>
<html lang="{% trans 'en' %}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
     --> 
   <title>{% trans "hello" %}</title>
</head>
  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="#">item</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                language
              </a>
              <ul class="dropdown-menu">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages  %}

                 {% for lang in languages %}
                 <li>
                  <a class="dropdown-item" href="/{{ lang.code }}/">
                    {{ lang.name_local }}
                  </a>
                 </li>
                  {% endfor %}
                
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav> 
         <div class="container">
            <p>item page</p>
           <p>{% trans "hello" %}</p>
         </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

authapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">Authentication <i class="fas fa-boxes"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:dashboard' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Dashboard</a>
            </li> {% endcomment %}
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'authapp:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{ user.username }}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'authapp:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'authapp:register' %}" class="btn btn-info">Register</a>
            </div>
            {% endif %}
        </span>
    </div>
</nav>